### ISSUE TITLE
程序无法开始

### ISSUE THREAD

**Issue by mayakovsji** [matrixsukhoi/voidmei#5]
Voidmei.exe可以正常启动，预览，保存位置，在开始后无任何反应。
error.log 如下
`[AWT-EventQueue-0] ERROR com.alee.utils.ProprietaryUtils - java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
	at java.base/java.lang.Class.getField(Class.java:1999)
	at com.alee.utils.ReflectUtils.getStaticFieldValue(ReflectUtils.java:440)
	at com.alee.utils.ProprietaryUtils.setupUIDefaults(ProprietaryUtils.java:103)
	at com.alee.laf.WebLookAndFeel.initComponentDefaults(WebLookAndFeel.java:537)
	at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
	at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1557)
	at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1544)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:939)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:927)
	at prog.app.initWebLaf(Unknown Source)
	at prog.app$3.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by Lutra-Fs** [comment]
try java 8

**Comment by Lutra-Fs** [comment]
See #3

**Comment by matrixsukhoi** [comment]
感谢@Lutra-Fs 大佬的建议，已增加Java版本判断
